import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import { theme } from "@/themes";
import Nav from "@/components/nav";
import Footer from "@/components/footer";
import { Container, ThemeProvider } from "@mui/material";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Nav/>
            
                 {children}
          
            {/* <br/> <br/>
            <br/> <br/> */}
            <Footer/>
          </ThemeProvider>
          
        </AppRouterCacheProvider>
        
        </body>
    </html>
  );
}
